### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [chiyingleung1/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by chileu** [comment]
Hi Billy - 
Thanks for your comment!  I have added the viewport meta tag to my application.html.erb file and deployed this change to heroku. I noticed that this fixed the responsive effect on my mobile device. One question though - is there a way I can view this effect on a web browser without actually having to go to my mobile device? 
- Chi

**Comment by BillyMassey** [comment]
Hi Chi -

There are iPhone, and various mobile browser emulators, but previewing it
with a real phone is generally the easiest way to go.

Hope this helps.

Cheers,

Billy
